adding Historical page and refractor analogies types to utils
MediaComem/carbonviz pull request #56
Opened 2023-05-11 11:37 UTC by jamest1903

2023-05-11 11:39 UTC, jamest1903 commented on webpack/src/utils/analogies.js
> +    marathon: {
Here I change from an array of objects to an object with keys names matching the different types. Before we fetched in array by index 0 -> 5

2023-05-11 11:56 UTC, jamest1903 commented on webpack/src/components/Analogies.vue
> +      <el-carousel-item v-for="(item, index) in analogyNames[dataType]" :key="index" label="." class="analogy">
We now pass in the name like "marathon" instead of an index of 0 to 4 to <analogy>

2023-05-16 08:56 UTC, slecorne requested changes

2023-05-16 08:56 UTC, slecorne commented on webpack/src/components/Analogies.vue
> +      <el-carousel-item v-for="(item, index) in analogyNames[dataType]" :key="index" label="." class="analogy">
please change `key` to not use index

2023-05-16 08:56 UTC, slecorne commented on webpack/src/components/AppFullpage.vue
> +    <div data-area="title" id="logoEquiwatt"></div>
can you take a higher resolution logo for the full page? looks blurry

2023-05-16 08:56 UTC, slecorne commented on webpack/src/composables/history.js
> +  const height = 15 + (amount / 0.9) * MAX_HEIGHT; // min 11px, max 150 px for 900g CO2eq ( 8h laptop consumption no activities ~ 200g)
update comment

2023-05-16 09:09 UTC, jamest1903 commented on webpack/src/components/Analogies.vue
> +      <el-carousel-item v-for="(item, index) in analogyNames[dataType]" :key="index" label="." class="analogy">
Will change to item

2023-05-16 10:39 UTC, jamest1903 commented on webpack/src/components/Analogy.vue
> +    index: {type: String},
changed to name

2023-05-17 06:25 UTC, slecorne approved these changes

2023-05-17 06:26 UTC, merged