Font styles
MediaComem/carbonviz pull request #93
Opened 2023-08-15 15:04 UTC by jamest1903

2023-08-15 15:25 UTC, slecorne requested changes

2023-08-15 15:25 UTC, slecorne commented on background/background.mjs
> +    if (!lastWeeklyDisplay.valueOf() || lastWeeklyDisplay < weekStartMonday) {
what happens if we are Tuesday at 17:00 and we showed the notification Monday at 9:00.
I have the impression that you would compare Mon 9:00 < Mon 17:00 and show the notification. Probably you need to set hours 00:00:00 for all cases

2023-08-15 15:25 UTC, slecorne commented on background/background.mjs
> +    if (!lastDailyDisplay.valueOf() || lastDailyDisplay.getDate() < now.getDate()) {
if you have a notification shown on a 31 of any month, you would never show anything again, no?

2023-08-15 15:25 UTC, slecorne commented on webpack/src/components/Popup.vue
> +/* dialog {
we can delete it I think

2023-08-16 07:16 UTC, jamest1903 commented on background/background.mjs
> +    if (!lastWeeklyDisplay.valueOf() || lastWeeklyDisplay < weekStartMonday) {
let weekStartMonday = new Date(now);
  if (!todayIsMonday) {
    weekStartMonday.setDate(now.getDate() - (now.getDay() + 6) % 7); // Calculate last Monday's date
  }
  weekStartMonday.setHours(0,0,0);

2023-08-16 11:50 UTC, slecorne approved these changes

2023-08-16 11:50 UTC, merged